### ISSUE TITLE
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable

### ISSUE THREAD

**Issue by jmrichardson** [tslearn-team/tslearn#254] opened 2020-06-01 20:44 UTC
Hi, I am running this [example](https://tslearn.readthedocs.io/en/stable/gen_modules/shapelets/tslearn.shapelets.ShapeletModel.html#tslearn.shapelets.ShapeletModel):
```
from tslearn.shapelets import ShapeletModel
from tslearn.generators import random_walk_blobs
X, y = random_walk_blobs(n_ts_per_blob=10, sz=16, d=2, n_blobs=3)
clf = ShapeletModel(n_shapelets_per_size={4: 5}, max_iter=1, verbose=0)
clf.fit(X, y).shapelets_.shape
clf.shapelets_[0].shape
clf.predict(X).shape
clf.predict_proba(X).shape
clf.transform(X).shape
```

I am getting this error on fit:
```
clf.fit(X, y).shapelets_.shape
Traceback (most recent call last):
  File "D:\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-20-c2ea172d56e6>", line 1, in <module>
    clf.fit(X, y).shapelets_.shape
  File "D:\Anaconda3\lib\site-packages\tslearn\shapelets.py", line 438, in fit
    self._set_model_layers(X=X, ts_sz=sz, d=d, n_classes=n_classes)
  File "D:\Anaconda3\lib\site-packages\tslearn\shapelets.py", line 600, in _set_model_layers
    )(transformer_layers[di]) for di in range(d)
  File "D:\Anaconda3\lib\site-packages\tslearn\shapelets.py", line 600, in <listcomp>
    )(transformer_layers[di]) for di in range(d)
  File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 75, in symbolic_fn_wrapper
    return func(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 463, in __call__
    self.build(unpack_singleton(input_shapes))
  File "D:\Anaconda3\lib\site-packages\tslearn\shapelets.py", line 131, in build
    trainable=True)
  File "D:\Anaconda3\lib\site-packages\keras\engine\base_layer.py", line 282, in add_weight
    constraint=constraint)
  File "D:\Anaconda3\lib\site-packages\keras\backend\tensorflow_backend.py", line 620, in variable
    value, dtype=dtype, name=name, constraint=constraint)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\keras\backend.py", line 845, in variable
    constraint=constraint)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 261, in __call__
    return cls._variable_v2_call(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 255, in _variable_v2_call
    shape=shape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 236, in <lambda>
    previous_getter = lambda **kws: default_variable_creator_v2(None, **kws)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2647, in default_variable_creator_v2
    shape=shape)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1434, in __init__
    distribute_strategy=distribute_strategy)
  File "D:\Anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1517, in _init_from_args
    raise ValueError("Tensor-typed variable initializers must either be "
ValueError: Tensor-typed variable initializers must either be wrapped in an init_scope or callable (e.g., `tf.Variable(lambda : tf.truncated_normal([10, 40]))`) when building functions. Please file a feature request if this restriction inconveniences you.
```

Any help would be appreciated.  TIA

**Comment by rtavenar** [comment] 2020-06-01 20:46
Hi

What is your tslearn version and how did you install it ?
What is your tensorflow version ?

Sent from a mobile device. Please excuse my brevity.

________________________________

**Comment by jmrichardson** [comment] 2020-06-01 20:52
Hi,

tensorflow==2.2.0
tensorflow-gpu==2.2.0
Keras==2.3.1
tslearn==0.3.1

Thanks so much for your help!  BTW, just the [integration ](https://tslearn.readthedocs.io/en/stable/integration_other_software.html) utilities alone is a life saver!

**Comment by rtavenar** [comment] 2020-06-01 20:53
Then this is a duplicate of #251 ;)

Glad you appreciate tslearn!

**Closed** 2020-06-01 21:36 UTC
Labels: bug
